[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["views/**", "public/gallery-placeholders/**"]

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8889
  publish = "public"
  autoLaunch = false

[[headers]]
  for = "/uploads/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
